### PR TITLE
Fix async dispatcher

### LINKED ISSUE #72: AsyncDispatcher seems to have synchronization issues
This is the first time this occurred: https://travis-ci.org/slide-rs/shred/jobs/339916332#L606

A test calling `mut_res` panicked :(

cc @kvark I think the problem is that `pulse` is using `Relaxed` ordering, so the `drop` call of the resources `Arc` gets moved after the pulse.

### PR DESCRIPTION
**Pull request by torkleyy**
Fixes #72

### CODE REVIEW

**Comment by kvark** [comment]
So long, pulse, and thanks for all the sync!

**Comment by torkleyy** [comment]
?

**Comment by kvark** [comment]
This removes pulse dependency for shred, and shred is used specs, for which pulse was made in the first place, so...

**Pull request merged**
