### PR TITLE
Add `MetaTable`s

### PR DESCRIPTION
**Pull request by torkleyy**
Still need to add documentation, but the logic is in place already.

### CODE REVIEW

**Comment by WaDelma** [comment]
I am not sure what this is used for, so I can't really do review for it.

**Comment by torkleyy** [comment]
See the docs, it's for registering trait implementations of resources. This will also be used for `AnyStorage`.

**Comment by torkleyy** [comment]
Rebased it. If you don't feel comfortable reviewing this PR, I can just as well wait for others to review it or merge it as-is.

**Comment by kvark** [comment]
What issue is being addressed here?

**Comment by torkleyy** [comment]
There's no specific issue filed, I just talked about it on Gitter a few times.

Here the motivation:

There's sometimes the need to call trait methods of resources where you don't know the specific type. Deleting components using `AnyStorage` is an example for that.

There are three problems with the current architecture:

1) the current solution needs an extra field in `World`, a `Vec` with raw fat pointers of `AnyStorage`s
2) the user cannot access that API to add their own custom component storages
3) for scripting you also want an API like this that allows you to access the trait implementations of arbitrary resources

This PR makes all that consistent allows easy access by the user.

**Pull request merged**
