### PR TITLE
Add support for thread-local resources

### LINKED ISSUE #45: Thread-local-resources
It would be nice to have thread-local-resources, as in, resources that do not implement Sync. 

It would be useful for systems that need access to things like `gfx::Device`, `gfx::Encoder` or `gfx::pso::buffer::ConstantBuffer`.

### PR DESCRIPTION
**Pull request by torkleyy**
I feel bad for using such a hack..

Somehow fixes #45, although I'm not sure if I can recommend using this.

### CODE REVIEW

**Comment by torkleyy** [comment]
I'm not even sure if this is 100% necessary. Allowing this might lead to more systems being thread-local, thus limiting concurrency. My personal preference is letting one (thread-local) system own the thread-local data and handle requests, which allows other systems to still run in parallel.

**Comment by torkleyy** [comment]
This would also require bumping the minimum version to 1.19

**Comment by Xaeroxe** [comment]
Your work here is pretty impressive, but I tend to agree with your assessment.  Resources only available to one thread sounds like an unnecessary complication that will just make the library harder to work with for little gain.

**Comment by omni-viral** [comment]
`ThreadLocal` may confuse people as it usually means "each thread gets a copy".

**Comment by torkleyy** [comment]
Ah maybe. My mental model was "this is a thread-local attribute **and** multiple threads have their own copy". So basically I see thread-local as "not shared between them".

**Pull request closed without merging**
