### PR TITLE
Implement dynamic resource IDs + example

### LINKED ISSUE #94: Cannot create dynamic `ResourceId`s
The [documentation](https://docs.rs/shred/0.7.0/shred/struct.ResourceId.html) states that a `ResourceId` is:
>The id of a Resource, which is a tuple struct with a type id and an additional resource id (represented with a usize).

However, it only contains a `TypeId`, which means there's no way to dynamically construct a `ResourceId`!

### PR DESCRIPTION
**Pull request by torkleyy**
Fixes #94

### CODE REVIEW

**Comment by torkleyy** [comment]
Still gotta add some more tests.

**Comment by torkleyy** [comment]
bors try

**Comment by Moxinilian** [comment]
I’d recommend using the word Dynamic instead of Scripting, as otherwise I think it would be too precise to serve it well.

Have you assessed the costs for the current workflow (performance and API-wise)?

**Comment by torkleyy** [comment]
> I’d recommend using the word Dynamic instead of Scripting, as otherwise I think it would be too precise to serve it well.

Oh, you mean in the example? I've used "dynamic" everywhere else AFAIK.

> Have you assessed the costs for the current workflow (performance and API-wise)?

I've done some benchmarking, there was no noticeable performance cost.

API-wise - it's definitely not a high-level API, but it's a very flexible low level API. It should be easy to define your scripting framework with that.

**Comment by torkleyy** [comment]
Thank you!
bors r=Moxinilian,jojolepro

**Pull request merged**
