### PR TITLE
Update rayon version

### PR DESCRIPTION
**Pull request by pengowen123**
Updates the rayon dependency version to 0.8.

### CODE REVIEW

**Comment by kvark** [comment]
Doesn't this require bumping the `shred` version?

**Comment by pengowen123** [comment]
I'm not sure what should happen when a dependency gets upgraded. I think the version will end up being bumped anyway when this change makes it to crates.io, so it should be okay.

**Comment by torkleyy** [comment]
Thanks for the PR @pengowen123!

While `rayon` is an internal dependency of shred, thus doesn't require a version bump, I think we shouldn't rush with upgrading to `0.8` since it would result to a duplicated inclusion of `rayon` in the final binary, because Specs still has `0.7` and updating it there would require a bump.

Please leave it open, so we don't forget to merge it once we're heading to the next release.

**Comment by pengowen123** [comment]
The `rayon` error has been fixed, so I have changed the PR to just include upgrading the `rayon` version. @torkleyy Will do!

**Comment by kvark** [comment]
If it's an internal dependency, I don't think having it duplicated should be much of a concern.

**Pull request merged**
